rules:
  idiomatic:
    no-defined-entrypoint:
      level: ignore
    use-contains:
      level: ignore
    use-if:
      level: ignore
  imports:
    use-rego-v1:
      level: ignore
    unresolved-reference:
      except-paths:
        - data.inventory.cluster.v1.Namespace
  style:
    line-length:
      # if any single word on a line exceeds this length, ignore it
      non-breakable-word-threshold: 30
