name: Run conftest-unittests.sh

on: [push, pull_request]

# Declare default permissions as read only.
permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  conftest:
    runs-on: ubuntu-latest
    env:
      # renovate: datasource=pypi depName=yq
      YQ_VERSION: 3.4.3
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Python
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5

      - name: Setup yq (pypi.org/project/yq/)
        run: |
          pip3 install yq==${YQ_VERSION}

      - name: Setup Bats
        uses: bats-core/bats-action@2104b40bb7b6c2d5110b23a26b0bf265ab8027db # 3.0.0

      - name: Setup Conftest
        uses: princespaghetti/setup-conftest@d75fd184422abf484802a0fefc0453f2cda20f95 # v1.1.23

      - name: Setup oc
        uses: redhat-actions/openshift-tools-installer@144527c7d98999f2652264c048c7a9bd103f8a82 # v1
        with:
          oc: "4"

      - name: Run _test/conftest-unittests.sh
        run: _test/conftest-unittests.sh

      - name: Tar and Generate hashes
        shell: bash
        id: hash
        run: |
          tar cvf policy.tar policy/

          echo "hashes=$(sha256sum policy.tar | base64 -w0)" >> "$GITHUB_OUTPUT"

      - name: Upload policy.tar
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4
        with:
          name: policy.tar
          path: policy.tar
          if-no-files-found: error
          retention-days: 5

    outputs:
      hashes: ${{ steps.hash.outputs.hashes }}

  provenance:
    needs: [conftest]
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      actions: read
      id-token: write
      contents: write
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v2.1.0
    with:
      base64-subjects: "${{ needs.conftest.outputs.hashes }}"
      upload-assets: true

  release:
    needs: [conftest, provenance]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    steps:
      - name: Download policy.tar
        uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e # v4
        with:
          name: policy.tar

      - name: Upload assets to release
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda # v2.2.1
        with:
          files: |
            policy.tar
