name: Check POLICIES.md is up-to-date

on: [push, pull_request]

# Declare default permissions as read only.
permissions: read-all

jobs:
  konstraint_doc:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Generate konstraint docs
        uses: redhat-cop/github-actions/confbatstest@0c6e3b63690cfa917a0ddc162efdfda3da82d66c # v4.4
        with:
          raw: konstraint doc -o POLICIES.md

      - name: Check if there are changes to POLICIES.md
        id: changes
        run: echo "changed=$(git status --porcelain POLICIES.md | wc -l)" >> $GITHUB_OUTPUT

      - name: Fail if POLICIES.md changes found
        if: steps.changes.outputs.changed >= 1
        run: |
          echo "Uncommited changes to POLICIES.md exist. Failing."
          echo 
          git status --porcelain
          git --no-pager diff POLICIES.md 
          exit 1

      - name: Link checker
        uses: gaurav-nelson/github-action-markdown-link-check@1b916f2cf6c36510a6059943104e3c42ce6c16bc # 1.0.16
