name: Check POLICIES.md is up-to-date

on: [push, pull_request]

jobs:
  konstraint_doc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate konstraint docs
        uses: redhat-cop/github-actions/confbatstest@v4
        with:
          raw: konstraint doc -o POLICIES.md

      - name: Check if there are changes to POLICIES.md
        id: changes
        run: echo "changed=$(git status --porcelain POLICIES.md | wc -l)" >> $GITHUB_OUTPUT

      - name: Fail if POLICIES.md changes found
        if: steps.changes.outputs.changed >= 1
        run: |
          echo "Uncommited changes to POLICIES.md exist. Failing."
          echo 
          git status --porcelain
          git --no-pager diff POLICIES.md 
          exit 1

      - name: Link checker
        uses: gaurav-nelson/github-action-markdown-link-check@1.0.13