name: Run opa-profile.sh

on: [push, pull_request]

# Declare default permissions as read only.
permissions: read-all

jobs:
  opa:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f086349bfa2bd1361f7909c78558e816508cdc10 # v2.8.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Opa eval --profile
        uses: redhat-cop/github-actions/confbatstest@e4729075dcd3f34946b80df6b1bfb952b9fee166 # v4
        with:
          tests: _test/opa-profile.sh
          policies: '[]' # An empty array is provided as the policies are already cloned via source.

      - name: Upload opa-profile.log
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4
        with:
          name: profile-results
          path: opa-profile.log
