name: Run opa-profile.sh

on: [push, pull_request]

# Declare default permissions as read only.
permissions: read-all

jobs:
  opa:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e # v2.10.4
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Opa eval --profile
        uses: redhat-cop/github-actions/confbatstest@0c6e3b63690cfa917a0ddc162efdfda3da82d66c # v4.4
        with:
          tests: _test/opa-profile.sh
          policies: '[]' # An empty array is provided as the policies are already cloned via source.

      - name: Upload opa-profile.log
        uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4
        with:
          name: profile-results
          path: opa-profile.log
