name: Lint policies with Regal

on: [push, pull_request]

# Declare default permissions as read only.
permissions: read-all

jobs:
  lint-policy:
    runs-on: ubuntu-latest
    env:
      # renovate: datasource=github-releases depName=StyraInc/regal
      REGAL_VERSION: v0.16.0
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - name: Check out code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Setup Regal
        uses: StyraInc/setup-regal@94ad2891f53efdb7ebe7c6836bc25ecc9504aec1 # v0.2.0
        with:
          version: ${{ env.REGAL_VERSION }}

      - name: Run Regal lint
        run: regal lint --format github policy
