name: Lint policies with Regal

on: [push, pull_request]

jobs:
  lint-policy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Regal
        uses: StyraInc/setup-regal@v0.2.0
        with:
          version: v0.10.1

      - name: Run Regal lint
        run: regal lint --format github policy
