name: Lint policies with Regal

on: [push, pull_request]

# Declare default permissions as read only.
permissions: read-all

jobs:
  lint-policy:
    runs-on: ubuntu-latest
    env:
      # renovate: datasource=github-releases depName=open-policy-agent/opa
      OPA_VERSION: v0.67.1
      # renovate: datasource=github-releases depName=StyraInc/regal
      REGAL_VERSION: v0.25.0
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup OPA
        uses: open-policy-agent/setup-opa@34a30e8a924d1b03ce2cf7abe97250bbb1f332b5 # v2.2.0
        with:
          version: ${{ env.OPA_VERSION }}

      - name: Setup Regal
        uses: StyraInc/setup-regal@33a142b1189004e0f14bf42b15972c67eecce776 # v1.0.0
        with:
          version: ${{ env.REGAL_VERSION }}

      - name: Run OPA Check
        run: opa check policy --strict

      - name: Run Regal lint
        run: regal lint --format github policy
